### ISSUE TITLE
NgModel binding not working in 'multiple' mode

### ISSUE THREAD

**Issue by bjoernw** [optimistex/ngx-select-ex#163]
On Init I'm trying to bind the select box to an already existing array of previously selected items and allow the user to edit the list. It does end up binding them fine once I select some but initially it does not the display the collection of items that I want to load it with. Am I doing something conceptually wrong here?
`
<ngx-select name="Relevant Contexts"
                        [items]="availableContextTypes"
                        [multiple]="true"
                        [optionTextField]="'name'"
                        [(ngModel)]="control.contextTypes"
                        placeholder="Select one or more contexts">
</ngx-select>
`

**Comment by optimistex** [comment]
@bjoernw Please, make an example there https://stackblitz.com/ to reproduce the bug and share a link to the example.

**Comment by bjoernw** [comment]
@optimistex i tried using that but couldn't get it working in stackblitz. Main question is do you allow users to pass a list of items from the server via ngModel and pre-populate the select box with those items? For me that never seemed to work. The binding works fine once i select things from the list of available items but the initial population never works.

**Comment by optimistex** [comment]
@bjoernw Check the example with delayed data populating.
Or check any other of the examples https://stackblitz.com/@optimistex
You can fork anyone and modify to show your issue.

**Comment by bjoernw** [comment]
@optimistex https://stackblitz.com/edit/angular-pu1lka-buse-gizem-uzunta
i would like for the select box to already have "selected" items when the page loads. Basically I want to synchronize a list on the server with a list in the browser. On page load i fetch the current list from the server and want those items to appear selected in the select box. How do I accomplish that?

**Comment by casper5822** [comment]
Same for me. We have to initialise the user selected values selected by users int the multiple selection. How can we do it?

**Comment by optimistex** [comment]
@bjoernw I've checked the example:
- the example is for a single select, but this issue is about the multiple select
- in the template is declared `[(ngModel)]="selectedCardFirst"` but there is no variable `selectedCardFirst`, so what behavior do you expect?

@casper5822 Could you make a stackblitz example with your issue. I'll check it out and try to help you.

**Comment by casper5822** [comment]
Thank you for the very quick feedback. Our case is very simple, before we use ng2-select in multiple select and the SelectComponet has a active field two load an array of values. So we download the user preferences from our server and with ng2-select we do selectComponet.active = users.preferences.  It's the same of .items field. 
The ngModel is not good for us because me have a list of object in this format  {id:"",text:""} and ngModel in ng2-select-ex wants only the ids

**Comment by optimistex** [comment]
@casper5822 If I understood correctly your needs, it should fit help you: https://codesandbox.io/s/scratch-angular-11-ngx-select-ex-9upjp?file=/src/app/app.component.ts
