### ISSUE TITLE
Unable to dynamically transpile ES module

### ISSUE THREAD

**Issue by rolodt** [optimistex/ngx-select-ex#26]
I imported as instructed and this error comes up.

Unable to dynamically transpile ES module↵   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.↵  Instantiating http://localhost:5557/node_modules/ngx-select-ex/ngx-select-ex.js↵  Loading http://localhost:5557/app/_shared/shared.module.js↵  Loading http://localhost:5557/app/app.module.js↵  Loading http://localhost:5557/app/main.js↵  Loading app/main

I'm using Angular 4 by the way. I have installed the proper version for angular 4.

**Comment by optimistex** [comment]
Try to use one of the bundles:
* /node_modules/ngx-select-ex/bundles/ngx-select-ex.umd.js
* /node_modules/ngx-select-ex/bundles/ngx-select-ex.umd.min.js

I have no other ideas because I have no experience with SystemJs.
________
If are you find out a solution then let me know in details. I will extend the documentation.

**Comment by wBatdeveloppement4** [comment]
Arf… :/
