### ISSUE TITLE
How to clear selected item from component / button

### ISSUE THREAD

**Issue by danielhasugian** [optimistex/ngx-select-ex#40]
how to remove items when i click reset in form, 
>           <ngx-select
>               *ngIf="child.code ==='ade'"
>                [multiple]="true"
>                [items]="searchItems"
>                autoClearSearch=" true"
>                optionValueField="code"
>                optionTextField="value"
>                [defaultValue]="selectChild2"
>                (select)="selectedNgx($event)"
>                (remove)="removedNgx($event)"
>               placeholder="Fill in the blank">
>           </ngx-select>
>          <input [hidden]="true" type="text" formControlName="childSelect2">

**Comment by optimistex** [comment]
**For first. **
Please, read the part of the documentation:
**Warning!** Although the component contains the `select` and the `remove` events, the better solution is using `valueChanges` of the `FormControl`.

```typescript
import {Component} from '@angular/core';
import {FormControl} from '@angular/forms';

@Component({
    selector: 'app-example',
    template: `<ngx-select [items]="['111', '222']" [formControl]="selectControl"></ngx-select>`
})
class ExampleComponent {
    public selectControl = new FormControl();
    
    constructor() {
        this.selectControl.valueChanges.subscribe(value => console.log(value));
    }
}
```
I mean, do not use the `select` and the `remove` events without a significant reason. Because it is a way into a headache.
__________
# The Answer to your question.
Use the `ngModel` or better the `formControl`.

**Comment by danielhasugian** [comment]
Oh thanks, it helps me

**Comment by mapsgeek** [comment]
i can't understand how this should help resetting the selected value from a button ?
if you please make it a bit clear

**Comment by optimistex** [comment]
> i can't understand how this should help resetting the selected value from a button ?
if you please make it a bit clear

Use formControl.

And clear value so: `formControl.setValue(null)`
