### ISSUE TITLE
Disabled item doesn't show correctly for bootstrap 3

### ISSUE THREAD

**Issue by Jrubzjeknf** [optimistex/ngx-select-ex#45]
In bootstrap 3, to disable a list item, the `disabled` class must be on the `li` element. Currently it is only on its child `a` element.

Suggested fix: also put the `disabled` class on the `li` element.

Sidenote: is the an example available somewhere with angular, bootstrap 3 and ngx-select-ex? I think I also found a bug related to click bubbling, but I'm not sure if that is related to my setup or the bootstrap version. It would also make it easier for me to show this bug.

**Comment by optimistex** [comment]
Take the example: https://stackblitz.com/edit/ngx-select-ex-issues-45
You may make a fork and to check your assumption.
___________
> Suggested fix: also put the disabled class on the li element.

Need to find other solution. Because the `a` tag used for children. Or need remake layout...
![image](https://user-images.githubusercontent.com/11228640/37708296-2c1e069a-2d17-11e8-8c02-40884526e9a1.png)

**Comment by Jrubzjeknf** [comment]
Ok, I doubt it's worth the effort. I don't need it at the moment, so never mind about it. Known issue? :)
